//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarSales.API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleSeller
    {
        public int ID { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public int SellerID { get; set; }
    
        public virtual Seller Seller { get; set; }
        public virtual VehicleAdvertisement VehicleAdvertisement { get; set; }
    }
}
